# Generated by Django 2.0.13 on 2019-07-17 12:23

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('layer2', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Router',
            fields=[
                ('device_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='layer2.Device')),
                ('ip_loopback', models.GenericIPAddressField(protocol='IPv4')),
            ],
            bases=('layer2.device',),
        ),
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(unique=True, validators=[django.core.validators.MinValueValidator(100), django.core.validators.MaxValueValidator(199)])),
                ('sourceIP', models.GenericIPAddressField(protocol='IPv4')),
                ('destinationIP', models.GenericIPAddressField(protocol='IPv4')),
                ('protocol', models.CharField(choices=[('TCP', 'TCP'), ('UDP', 'UDP'), ('ICMP', 'ICMP')], max_length=6)),
            ],
        ),
        migrations.AddField(
            model_name='router',
            name='rules',
            field=models.ManyToManyField(related_name='rules', to='layer3.Rule'),
        ),
    ]
