# Generated by Django 2.0.13 on 2019-07-17 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('layer3', '0002_rule_action'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterfaceRouter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_int', models.CharField(max_length=20)),
                ('mac', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('UP', 'UP'), ('DOWN', 'DOWN')], max_length=5)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='layer3.Router')),
            ],
        ),
    ]
